import { findByStoreNameLazy } from "@metro/wrappers";

export const UserStore = findByStoreNameLazy("UserStore");
export const SelectedChannelStore = findByStoreNameLazy("SelectedChannelStore");
export const MessageStore = findByStoreNameLazy("MessageStore");
export const ChannelStore = findByStoreNameLazy("ChannelStore");
export const PrivateChannelSortStore = findByStoreNameLazy("PrivateChannelSortStore");
export const ReadStateStore = findByStoreNameLazy("ReadStateStore");
export const GuildRoleStore = findByStoreNameLazy("GuildRoleStore");
export const GuildMemberStore = findByStoreNameLazy("GuildMemberStore");
export const PresenceStore = findByStoreNameLazy("PresenceStore");
export const SessionsStore = findByStoreNameLazy("SessionsStore");
export const StickersStore = findByStoreNameLazy("StickersStore");
export const SelectedGuildStore = findByStoreNameLazy("SelectedGuildStore");
export const EmojiStore = findByStoreNameLazy("EmojiStore");
export const GuildStore = findByStoreNameLazy("GuildStore");
export const SortedGuildStore = findByStoreNameLazy("SortedGuildStore");
export const UserGuildSettingsStore = findByStoreNameLazy("UserGuildSettingsStore");
export const GuildReadStateStore = findByStoreNameLazy("GuildReadStateStore");
export const PermissionsStore = findByStoreNameLazy("PermissionStore");
export const UserSettingsProtoStore = findByStoreNameLazy("UserSettingsProtoStore");
